### ISSUE TITLE
S2 P1 - BUG Unexpected Crash on Settings Page

### ISSUE THREAD

**Issue by mrtndwrk** [muhlba91/fh-burgenland-bswe-3b#12]
Bug Report: Unexpected App Crash on Settings Page
Issue Title: Application crashes when accessing the Settings page

Environment:

Operating System: Windows 10 Pro, Version 1337
Browser: Google Chrome v12315236
Software Version: App v2.3
Hardware: Dell XPS 15

Steps to Reproduce:

Open App.
Click on the user icon in the top right corner.
Select "Settings" from the dropdown menu.

Expected Behavior:
Settings page should open, allowing users to modify their preferences.

Actual Behavior:
Application crashes immediately upon selecting "Settings" and a generic "Application has stopped working" error pops up.

Logs/Screenshots:
Attached are logs of the error message.

Additional Information:

The issue is consistent across multiple user accounts on the same machine.
A friend on MacOS reported the same issue, suggesting it's not platform-specific.
Possible Workaround:
Restarting the app doesn't seem to help, as the error is reproducible. Accessing settings from another section of the app (e.g., the Help page) also results in a crash.

**Comment by muhlba91** [comment]
as discussed, i agree with the contents.
priority is related to context and interpretation - e.g. if settings contain setting the maximum transaction amount this is definitely a P1; if it's just profile settings P2 would suffice too.
